### ISSUE TITLE
How to add radio options to a column custom formatter/editor?

### ISSUE THREAD

**Issue by ng7323** [olifolkerd/tabulator#127]
Hi, 
I have had a go a setting a column with a custom formatter/editor, I couldn't get it to work with radio options (newbie to jQuery).

Can someone provide an example on how to setup radio options in the column.

I would like background colour to be changed on value of the column (should be able to manage this myself), and an editor to do RAG rating 
i.e. R = Red, A = Amber, G = Green, I would like it to be a one click change i.e. R selected, click on G would instantly set the column value to G etc. not like a dropdown choice change.
Guess it doesn't have to be radio choices on the editor side or just buttons/images with highlighting the selected value choice.

**Comment by olifolkerd** [comment]
Hey,

Here is an example of a custom radio button editor and how to bind it to a column:
```js
//define custom editor
var radioEditor = function(cell, value, data){
	//create and style radio buttons
	var radio = $("<form>Red:<input name='rag-radio' type='radio' value='red'> Amber:<input name='rag-radio' type='radio' value='amber'> Green:<input name='rag-radio' type='radio' value='green'></form>");
	radio.css({
		"padding":"4px",
		"box-sizing":"border-box",
	});

	//set the value of the radio buttons
	if(value){
		$("input[value=" + value + "]", radio).prop("checked", true);
	}

	//focus on first radio button
	if(cell.hasClass("tabulator-cell")){
		setTimeout(function(){
			$("input:first", radio).focus();
		},100);
	}

	//submit new value on selection
	$("input", radio).on("change", function(e){
		var chosen = $("input:checked", radio);
		cell.trigger("editval", chosen.length ? chosen.val() : "");
	});

	//submit new value on blur event to non radio button
	$("input", radio).on("blur", function(e){
		if($(e.relatedTarget).attr("name") != "rag-radio"){
			var chosen = $("input:checked", radio);
			cell.trigger("editval", chosen.length ? chosen.val() : "");
		}
	});

	return radio;
};

//build table with editor bound to color column
$("#example-table").tabulator({
    columns:[
        {title:"Color", field:"color", editor:radioEditor},
    ],
});
```

Let me know how it goes for you, and if you have any other questions :)

Oli

**Comment by ng7323** [comment]
Thanks Oli, 
That worked well, is there a way to show the radio options by default i.e. so you don't have to click the field to show the editor.
Also I have just tried the grid with IE 11 (W7) and on your website and the examples, they don't seem to run, on IE there is a scripts or active x control blocked, but even allowing that provides no grid.  On Windows 10 Edge the grid works as chrome.

**Comment by olifolkerd** [comment]
Hey,

Thanks for the heads up, there was a bug affecting IE11, which is now fixed.

And with regards to the formatter, with a few tweaks to the code for the editor, we can turn it into a formatter that also alters the cell value:

```js
//define custom formatter
var raidoFormatter = function(value, data, cell){
	//create and style radio buttons
	var radio = $("<form style='margin-bottom:0;'>Red:<input name='rag-radio' type='radio' value='red'> Amber:<input name='rag-radio' type='radio' value='amber'> Green:<input name='rag-radio' type='radio' value='green'></form>");

	//set the value of the radio buttons
	if(value){
		$("input[value=" + value + "]", radio).prop("checked", true);
	}

	//submit new value on selection
	$("input", radio).on("change", function(e){
		var chosen = $("input:checked", radio);
		cell.trigger("editval", chosen.length ? chosen.val() : "");
	});

	//submit new value on blur event to non radio button
	$("input", radio).on("blur", function(e){
		if($(e.relatedTarget).attr("name") != "rag-radio"){
			var chosen = $("input:checked", radio);
			cell.trigger("editval", chosen.length ? chosen.val() : "");
		}
	});

	return radio;
};

//build table with editor bound to color column
$("#example-table").tabulator({
    columns:[
        {title:"Color", field:"color", formatter:raidoFormatter},
    ],
});
```

**Comment by ng7323** [comment]
Thanks again Oli, will implement your formatter tomorrow.

I have just noticed the example Filter Data In Header has a bug on the driver column heading filter, i.e. it doesn't filter the column, in IE or chrome.  

I see also a the examples from Persistent Column Layout would also not to be working in IE it appears to break all of the grids after that example.  Sorry to give you the bad news.

I was also wondering, do you have an example of using a formatter to use another column/cell value instead of the one being formatted. i.e. color the name cell based on the value from the favorite color column.

**Comment by olifolkerd** [comment]
Thanks for the additional feedback.

- I cant seem to replicate your issues with the column filtering, it has worked on every browser i have tried. are your talking about the demo featured [here](http://olifolkerd.github.io/tabulator/examples/#filter-header)?

- The persistent column layout issue should now be resolved as well, although i couldn't see it breaking any of the other examples after it either. are you talking about the examples on the website or those that come with the tabulator.js library.

Thanks for you help with this :)

**Comment by ng7323** [comment]
Thanks Oli, the formatter worked perfectly managed to add CSS style to do the background.

Yes your demo link is the one I was referring to and the following examples.  As to the bug about filter, I have just tested on IE11 W7 11.0.9600.18524 Update Version 11.0.37 KB3197655, also just tested with W7 Chrome Version 54.0.2840.99 m, both appear to fail to filter, also tested with IE11 11.576.14393.0 Update Version 11.0.38 KB3203621 on W10 also fails.
Yes I can confirm the other tables are also now working unlike what it looked like yesterday maybe you were updating something when I saw the problem.

Another stupid question, if IE is set to compatibility mode, should the table work IE11, or does is only work in default mode.

**Comment by olifolkerd** [comment]
which column are you having trouble filtering? as i am struggling to find one that doesn't work on any of my browsers (have you tried force refreshing the page in case you have an old version of tabulator cached). do you get any error messages in the console when you try to filter?

The problem with the others was invalid persistent storage values cached from an old version of tabulator, I changed the id and it fixed itself.
 
No questions are stupid, they are all welcome here! I must admit ive never tried the compatibility view when testing. Having just given it a go it all seems to work fine. if you are having any issues, let me know the settings on the browser and tabulator that you are using and i will see if i can fix them for you.

**Comment by ng7323** [comment]
I was only clicking the tick box column (Driver), tried CTRL-F5 etc.. doesn't fix it. . 
console says 2551 tabulator.js
TypeError: filters[field].toLowerCase is not a function
    at e.(anonymous function).(anonymous function).colFilter [as filterField] (http://olifolkerd.github.io/tabulator/js/tabulator.js:2551:59)
    at e.(anonymous function).(anonymous function)._filterRow (http://olifolkerd.github.io/tabulator/js/tabulator.js:1563:17)
    at e.(anonymous function).(anonymous function)._filterRow (http://olifolkerd.github.io/tabulator/js/jqueryui.js:6:7987)
    at http://olifolkerd.github.io/tabulator/js/tabulator.js:1526:17
    at Array.filter (native)
    at e.(anonymous function).(anonymous function)._filterData (http://olifolkerd.github.io/tabulator/js/tabulator.js:1525:32)
    at e.(anonymous function).(anonymous function)._filterData (http://olifolkerd.github.io/tabulator/js/jqueryui.js:6:7987)
    at e.(anonymous function).(anonymous function).setFilter (http://olifolkerd.github.io/tabulator/js/tabulator.js:1485:8)
    at e.(anonymous function).(anonymous function).setFilter (http://olifolkerd.github.io/tabulator/js/jqueryui.js:6:7987)
    at updateFilter (http://olifolkerd.github.io/tabulator/js/tabulator.js:2565:9)

**Comment by olifolkerd** [comment]
Ahh, the driver column was the one column i hadnt checked, I will look into that right now!

**Comment by ng7323** [comment]
I have just re-tested IE11 (w7) with compatibility mode enabled, it works fine, I think I turned it on but didn't CTRL-F5 tabulator examples page, thus the tables didn't load, CTRL-F5 fixed it, must have been cached or something.

**Comment by olifolkerd** [comment]
Turns out there is an issue with correctly reading the value of the checkbox header filter. i have temporarily removed the column from the demo until i get a chance to look into it at the weekend.

Thanks for your thorough reporting, it has been a great help!

Keep up the good work :)

**Comment by ng7323** [comment]
I hate to say it, check the filter of gender male, it must be doing contains or something so male filters for both female and male.

**Comment by olifolkerd** [comment]
You are correct! hmm, i will have a look into it this weekend, something in the last version update must have had a knock on effect on some of the header filters

**Comment by ng7323** [comment]
by the way excellent table.  keep it up...

**Comment by olifolkerd** [comment]
Thanks, great to hear you are enjoying it.

Thanks for the help finding the bugs, it only gets better!

**Comment by olifolkerd** [comment]
I have committed a fix for the header filtering.

all elements now look for an exact match of data except for non numeric input elements which will accept a partial match with the typed string.

Full details can be found in the updated documentation [here](http://olifolkerd.github.io/tabulator/docs/#header-filters)

give me a shout if you find any other issues.

Cheers

Oli
