### ISSUE TITLE
Rows not displaying at foot of table with height attribute set, Firefox, Edge

### ISSUE THREAD

**Issue by gso** [olifolkerd/tabulator#2117]
**Describe the bug**
Using Microsoft Edge and Firefox, when I set the height for the table, the bottom few rows of the table do not display.  It works fine using Chrome and Chromium (haven't had chance to test Safari yet). 

**Tabulator Info**
Using `https://unpkg.com/tabulator-tables@4.2.5/dist/js/tabulator.min.js`
```
    table = new Tabulator( "#table", {
    	height: $( window ).height() - document.getElementById( 'table' ).getBoundingClientRect().top - 5,
     	columns: [ //Define Table Columns
       	 	{ title:"Date", field:"date", width: 125, headerSort:false },
    	 	{ title:"Description", field:"description", width:250, headerSort:false },
    	 	{ title:"Income", field:"income", width:110, align:"right", sorter:"number", headerSort:false, 
    	 		formatter:"money", formatterParams:{symbol:"£"} },
       	 	{ title:"Outgoing", field:"outgoing", width:110, align:"right", sorter:"number", headerSort:false, 
       	 		formatter:"money", formatterParams:{symbol:"£"} },
       	 	{ title:"Running Total", field:"runningtotal", width:110, align:"right", headerSort:false, 
       	 		formatter:"money", formatterParams:{symbol:"£"} },
       	 	{ width: 30, headerSort:false, formatter:function( cell, formatterParams ) {
       	      const rowData = cell.getData();  // returns data for row
              if ( rowData.runningtotal < 0) {
                  return "<span style='color:red; font-weight:bold;'>DR</span>";
              } else if ( rowData.runningtotal >= 0) {
                  return "";
              } else {
            	  throw new Error();
              }
            } }
     	]
    } );
```
**Working Example**

**To Reproduce**
Load more rows into a table than the height attribute of the table will display using Firefox or Microsoft Edge.  Reproduced with the following HTML:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <link href="https://unpkg.com/tabulator-tables@4.2.7/dist/css/tabulator.min.css" rel="stylesheet">
  <script src="https://unpkg.com/tabulator-tables@4.2.7/dist/js/tabulator.min.js"></script>
  <style>
    // Wrap tabulator column headers
    .tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title {
    	white-space: normal;
	}
  </style>
  <script>
  $( function() {

    var tabledata = [];
    for(var i=0; i<100;i++) {
    	tabledata.push({ test: `test ${i}` });
    }    
    var table = new Tabulator( "#table", {
    	height: $( window ).height() - document.getElementById( 'table' ).getBoundingClientRect().top - 35,
    	data: tabledata, //assign data to table
     	columns: [ //Define Table Columns
    	 	{ title:"Test", field:"test", width:300, align:"center", headerSort:false },
    	 	{ title:"A Very Long Title Header", field:"test2", width:150, align:"center", headerSort:false },
     	]
    } );
  } );
  </script>
</head>
<body>

<div id="table"></div>

</body>
</html>
```

**Expected behavior**
Display all rows that will fit into the height attribute given.

**Screenshots**
![Chromium](https://user-images.githubusercontent.com/1710503/58768183-f263fc80-858e-11e9-84ea-c0fb736ef3c6.png) - Chromium, how the table should look
![Firefox](https://user-images.githubusercontent.com/1710503/58768193-0dcf0780-858f-11e9-8aac-82693e6cf51f.png) - Firefox, rows not showing at the base of the table

**Desktop (please complete the following information):**
 Both Windows 10 and Ubuntu.  Current versions of Chromium, Chrome, Firefox, Microsoft Edge.

**Additional context**

**Comment by tentus** [comment]
Post a jsfiddle and I'll take a look

**Comment by gso** [comment]
It works on JSFiddle, the HTML seems to run in a frame.  If you cut and paste the HTML in the To Reproduce section above and multiply the `tabledata` and run the page in Firefox you should see what I mean.

**Comment by tentus** [comment]
The purpose of asking for a fiddle was to ensure that there are no small inconsistencies between yourself and the N number of people who try to reproduce the issue after you. Point in case, pasting your code fails, because you have a syntax error in the middle of the tabledata array. You also use a different version of tabulator in your example.

So, here's a fiddle actually demonstrating the issue:
https://jsfiddle.net/78esufwr/

The issue also occurs if you use a css string like `"calc(100vh - 50px)"`.

**Comment by gso** [comment]
It works fine in JSFiddle for some reason, but run the code in Firefox and the last half dozen lines of the table do not display.  I've updated the code in the **To Reproduce** section, if you paste this into a page and load it into Firefox you should see what I mean.

I don't think I've used any css like `calc(100vh - 50px)`.

**Comment by timothymarois** [comment]
I can confirm I am having the same issue, using Firefox. 

The table wrapper:

![Screenshot 2019-06-04 18 45 54](https://user-images.githubusercontent.com/2489333/58918736-8c47b880-86f9-11e9-9508-c7a4ef04d27a.png)

The table contents get pushed because of padding: (gets worse the more you scroll)

![Screenshot 2019-06-04 18 46 04](https://user-images.githubusercontent.com/2489333/58918739-923d9980-86f9-11e9-85f3-49add6662166.png)

**Comment by timothymarois** [comment]
> The issue also occurs if you use a css string like "calc(100vh - 50px)".

@tentus How do you solve the issue if using this? because it works great in chrome, and this height calculation is incredibly important for device sizes, esp when building management interfaces.

**Comment by tentus** [comment]
@timothymarois the css calc doesn't solve the issue, my comment was that the issue reproduces even if you use handy tricks like that. I had looked to see if maybe there was a way to solve the issue with nesting the container and was unsuccessful.

From taking another look this morning, there does seem to be some workarounds with declaring the `virtualDomBuffer` explicitly (a value of "100" (not the number 100, the string) seemed to fix it for me). That said, that seems like probably a bug itself, so I hesitate to recommend it.

**Comment by timothymarois** [comment]
@tentus I can't seem to get `virtualDomBuffer` to have any effect for me. I don't think that is a workaround. Unless I am doing it wrong, but it either made spacing worse or made no effect. 

I'm linking this because it seems somewhat related: https://stackoverflow.com/questions/53381922/tabulator-list-items-disappear-when-scrolling-virtualdombuffer-issue

**Comment by timothymarois** [comment]
@tentus One thing I do notice with using `virtualDomBuffer:'100'`, it dramatically slows down the loading of `ajaxProgressiveLoad scroll`, especially on Chrome.

**Comment by gso** [comment]
`virtualDomBuffer:'100'` works in Firefox, but in Chrome the scroll bar seems to lock periodically when scrolling down the page, jumping to the very bottom from about two thirds the way down, it scrolls upwards OK.

**Comment by tentus** [comment]
Ah, I just realized why the string version behaves as it does. Obvious in retrospect: it's getting added to height in a number of places, which javascript would treat as a concatenation. In other words, 
```"100" + 200 == "100200";```

So the reason it's appearing to work around the issue is because it's blasting the comparisons into comically large numbers.

I really need to start drinking coffee _before_ I look at code. -_-

**Comment by timothymarois** [comment]
@tentus Good find, that would make sense. I notice Firefox is substantially faster than Chrome, just in general, which might make sense why Chrome is bogging down with this height calculation. I will leave this off for now. but really would need a fix for Firefox. Has to be a solution to this.

**Comment by tentus** [comment]
For now your best bet is probably to set the `virtualDomBuffer` to a large-but-not-unreasonable value (I use 1600 in a project of my own). This comes at the cost of some performance but at least it runs somewhat tolerably, depending on the complexity of your tables.

BTW, you might want to read thru https://github.com/olifolkerd/tabulator/issues/1437, which is kind of the hub for performance tricks and woes at the moment.

**Comment by gso** [comment]
```
    	virtualDomBuffer: 1600,  // fix for blank rows bug
```
Works in Firefox, Edge and Chrome.  Thanks for that.

**Comment by olifolkerd** [comment]
Hey Chaps,

This is because you are resizing your table after it is defined without calling the ***redraw***. Because an element in a browser has no way of knowing when it is resized you have to tell tabulator in order for it to adjust its virtual DOM rendering window.

The reason this dosn't happen in chrome is because chrome implements the ES8 Resize Observer feature, which tabulator uses to know when it has been resized.

When this is implemented in other browsers it will become a non issue,

This particular topic is covered extensively in the documentation, and i must have answered the exact same question at least ***50*** times in this issue list, so i would love to know where i can put this answer that people will see more readily because im running out of spaces to post it.

Any feedback on where you would expect to see this info would be great

Cheers

Oli :)

**Comment by gso** [comment]
```
    var table = new Tabulator( "#table", {
    	height: $( window ).height() - document.getElementById( 'table' ).getBoundingClientRect().top - 35,
    	data: tabledata, //assign data to table
     	columns: [ //Define Table Columns
    	 	{ title:"Test", field:"test", width:300, align:"center", headerSort:false },
    	 	{ title:"A Very Long Title Header", field:"test2", width:150, align:"center", headerSort:false },
     	]
    } );
    table.redraw();
```
Not sure how I am resizing the table after is is defined, the height attribute is set during the definition, the above does however work, cheers.

**Comment by timothymarois** [comment]
@olifolkerd Thank you. The `redraw()` does solve the problem.

**Comment by gso** [comment]
@olifolkerd a note on the need for `table.redraw` to enable the table to work across all browsers should be added to the help pages when `new Tabulator( ... )` is explained.

**Comment by olifolkerd** [comment]
@gso it isn't needed by default. It is only needed if you are creating your table on a hidden element.

If it is defined on a visible element in the body it will handle the residing automatically.

For the majority of users they will need to do nothing to work cross browser.

The table must be visible when being laid out in order for tabulator to calc the size of the elements  as hidden elements have no height till they are first shown

**Comment by gso** [comment]
@olifolkerd Is not the `<div id="table"></div>` in the Working Example above visible?
