### ISSUE TITLE
Table contents sometimes disappear when scrolling horizontally

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3163]
**Describe the bug**
In tables with a lot of content, scrolling horizontally sometimes makes the table contents turn invisible.

Workaround:
- manually resizing a column fixes it
- It happens again once the table is re-rendered

**Tabulator Info**
- 4.9.3

**Working Example**
I'm working on it! Please don't close yet, let me figure it out :-)

**To Reproduce**
Also working on it!

**Expected behavior**
Table contents should render clearly

**Screenshots**

![invisible](https://user-images.githubusercontent.com/279769/104929900-1e9dde00-596a-11eb-87fd-54abc68a51df.png)

**Desktop (please complete the following information):**
- Beekeeper Studio (latest) / Electron

see: https://github.com/beekeeper-studio/beekeeper-studio/issues/445

**Comment by rathboma** [comment]
Having a hard time replicating it in the browser, but here's some more information:

- only happens when virtualDomHoriz is true
- Seems to happen when a specific column starts scrolling off screen (eg email in the screenshot above)
- When it happens all the `tabulator-cell` divs totally disappear, so the `tabulator-row` divs are totally empty

I'll try and capture a gif/video

**Comment by rathboma** [comment]
![Peek 2021-01-18 16-01](https://user-images.githubusercontent.com/279769/104938091-807c3900-59a6-11eb-8662-4574da9107a4.gif)

**Comment by olifolkerd** [comment]
Is there a very wide column in the table?

Do you have an example table configuration and dataset that can replicate this?

**Comment by rathboma** [comment]
Wide column: yes-ish, description is fairly large.
I tried setting `columnMaxWidth` to 125 (that is present in the example), same behavior.

Let me get this dataset and see if I can replicate in the browser. So far I've been unable to replicate. I can tell you how to replicate in beekeeper if that helps?

**Comment by rathboma** [comment]
This is the data in the table: https://gist.github.com/rathboma/df808d0c54da16d7925865f4a198aeb2

**Comment by rathboma** [comment]
I can't replicate it in a fiddle right now, but working on it.

**Comment by rathboma** [comment]
The biggest difference I see between this table and the one in a fiddle, is the region marked for `tabulator-table`:
![image](https://user-images.githubusercontent.com/279769/104940110-35aff080-59a9-11eb-80f2-474de4def90c.png)

The `tabulator-holder` is where you'd expect it to be

**Comment by olifolkerd** [comment]
Usually if it can't be replicated in a fiddle it is the result of a wierd interaction with its environment.


To give you an idea of what is going on, when you  scroll a table with the hoz vdom enabled it removes columns from one side at the same time as adding them to the other. If you scroll fast by quickly dragging the scroll bar and that scroll exceeds the width of the table in one go then instead of removing and adding columns it emptys the table and redraws it because it is faster. It may be that when this fast scroll is occuring the redraw is being blocked for some reason. Maybe related to data in a column or a table layout option. This is why resizing or scrolling again fixes it because it triggers a fresh redraw of the table

**Comment by rathboma** [comment]
Interesting. So I just tested scrolling really fast: the bug doesn't occur. So the full redraw skips the issue, so it's an issue with the slow scroll behavior.

Yes I think there's something funky going on with how we lay it out. I'm trying to simply replicate that, but to no success so far.

So it seems to be an issue with it removing the columns and re-adding them (I guess they're not re-adding). Any pointers to where in the code I could look for that?

**Comment by olifolkerd** [comment]
Do you have an example column definition array for the ones in the table
when in breaks?

Is the table contained in a flexbox by any chance?

**Comment by rathboma** [comment]
Yes it is in a flexbox. I can get you the column definitions

**Comment by rathboma** [comment]
gist (bit funky due to formatters and such):
https://gist.github.com/rathboma/5bc9d6f85142fcd0aedb5ce73638cc4f

**Comment by rathboma** [comment]
Looks to be `flex-grow: 1;` in the css for the surrounding div causing the issue in some way. If I remove that one line, it seems to be fixed? No idea if that fixes it for all situations though

**Comment by olifolkerd** [comment]
i would suggest putting tabulator in a div with a width of 100% inside of a flexed container, does that help?

are you just using flex or flexgrid?

**Comment by rathboma** [comment]
Update, that didn't fix it.

**Comment by olifolkerd** [comment]
hmmmm, without a reproducible example this could be very tricky to fix.

If you take the exact table configuration and data and run in it a browser does it work?

**Comment by olifolkerd** [comment]
are you seing any console errors?

**Comment by rathboma** [comment]
No console errors. From what I can tell, it works in browsers, but I can't replicate the UI exactly. It's possible this is a symptom of Electron - the version of Chromium it uses is fairly old. I'll keep trying to reproduce

**Comment by olifolkerd** [comment]
what happens if you try it in an empty electron wrapper?

**Comment by rathboma** [comment]
Ok. I replicated it, in Chrome:

https://jsfiddle.net/rathboma/0x9qcLmn/4/


Make the display window fairly small, then hold the scroll bar and scroll right at a not-too-fast speed

**Comment by rathboma** [comment]
https://user-images.githubusercontent.com/279769/105231246-30c77a00-5b2c-11eb-87c4-bee6cb1084df.mov

**Comment by olifolkerd** [comment]
Amazing, I will have a play with it in the morning and see if I can get to the bottom of it

**Comment by rathboma** [comment]
I'm still not 100% able to consistently reproduce it. Try with a non-maximized window if you can't get it initially. Let me know how it goes

**Comment by rathboma** [comment]
Some notes for replication:
- If you resize the window, or resize a column, it will work normally, so you'll need to `run` again
- I have the best luck replicating when the display area isn't too big and isn't too small, this is the same in beekeeper. It happens less often if the window is full screen
- It may take several tries to get the behavior to happen, with different sized windows, just don't forget to `run` after you change anything

**Comment by olifolkerd** [comment]
Hey @rathboma 

Ive had a play with the demo *(thanks a lot for setting that up, big help)* and i think the reason it is happening is along the lines of my initial suggestion.

When i built the initial version of the horizontal DOM it was don on the assumption that the table would always be wider than the widest column. when that table is small (and in this case has a wide column), it has columns that are wider than the entire width of the table, which causes the scrolling maths to get upset as the column it adds then exceeds the left edge of the table and is then immediately removed.

Resizing or redrawing triggers a redraw from the current position which then fixes the issue.

This should be a fairly quick fix to get in, i will have a play on sunday and see if i can get a patch release out for you.

In the mean time as a temporary work around, if you set the max width of a column to under the width of the table, either using the `columnMaxWidth` property to set it globally or `maxWidth` in a column definition you should be able to avoid the issue

Cheers

Oli :)

**Comment by rathboma** [comment]
@olifolkerd thanks for looking so quickly! 

Unfortunately when setting max column width it still happens :-(. Not sure if in the demo? Maybe? But definitely in the app. Maybe the math is based on content width, not cell width somehow?

**Comment by rathboma** [comment]
you can see the column widths in my original gif of the app -- they're 125px and it's still happening

**Comment by olifolkerd** [comment]
Hey @rathboma 

I've pushed an update to master which fixes the issue i managed to reproduce at least *(i will hold of doing a release until you are happy that it works)*

The issue was arising on tables with widely varying column widths, when using the hoz virtual DOM the table is not aware of the actual width of columns not in the view port  when in `fitData` layout mode because the content hasnt been loaded yet, so it just works out an average column width of the visible columns and then uses that to work out the scroll bar size for the columns outside the viewport. it then adjusts these as you scroll to take account of the actual column widths.

There was an issue with the recalculation maths which was cumulative as you scrolled the table eventually shifting what tabulator thought was the visible area of the table to outside the view port.

Would you mind pulling down master and see if it helps?

If it dosn't, then I may need a bit more info and an updated demo. Does the table allways start scrolled to the left when the data is loaded?

Cheers

Oli :)

**Comment by rathboma** [comment]
Thanks Oli! I'll look tonight.

One other option that might work:

What if I could provide an initial column width for all columns in the column spec? Would that be helpful?

**Comment by rathboma** [comment]
Yes the table always starts scrolled to the left

**Comment by rathboma** [comment]
Still happening I'm afraid :-(


![Peek 2021-01-24 22-06](https://user-images.githubusercontent.com/279769/105660388-7f5c7780-5e90-11eb-8e07-a3732f04ecc7.gif)

**Comment by olifolkerd** [comment]
Dam, that sucks.

I am really struggling to replicate that in the browser.

Is there any way I could test it in app?

Cheers

Oli

**Comment by rathboma** [comment]
Having trouble re-replicating in the app now. I'll play in the AM and send you instructions.

**Comment by rathboma** [comment]
Ok, here's how to replicate:
1. Download 'sakila.db' from here - https://github.com/jOOQ/jOOQ/tree/main/jOOQ-examples/Sakila
2. check out beekeeper branch `tabulator-hot-fix`
3. `yarn install`
4. `yarn run electron:serve` - should work on any platform
5. When the app opens, open the sqlite database
6. Make sure the Beekeeper Window is smallish
7. Click on `film` in the left sidebar
7. Scroll to the right slowly, see disappearing columns
8. NOTE - if you click `search` to refresh the data, it will work fine. To replicate, close then re-open the tab

**Comment by rathboma** [comment]
This is what you will see:

![Uploading Peek 2021-01-25 09-25.gif…]()

**Comment by rathboma** [comment]
I'm not sure if I emphasized this earlier, but I am totally willing to give the columns each and initial width so that your algorithm will be able to know exactly how wide the columns are..


Would this help solve this particular bug?

**Comment by olifolkerd** [comment]
Yeah if you fix them all to the same width and change the layout mode to fitColumns that should prevent the issue.

Let me know if that works for you. If it does I will hold out on a patch release to resolve the issue fully til 5.0 in a couple of months time because I'm rebuilding the hoz vdom in that

**Comment by chumaltd** [comment]
This looks as the same issue as I reported in #3149. Fixed column `width` attribute on setup works for me.
And, I also have large row height just after the 21st rows. In my case, JSON parsed data has no trouble, but supplied from Redux causes sizing issue.

**Comment by rathboma** [comment]
Fix coming this weekend

**Comment by olifolkerd** [comment]
Have you gotten to the bottom of it?

**Comment by rathboma** [comment]
Oops no, commented on the wrong project and issue lol

**Comment by Joao-deOliveira** [comment]
Hi @olifolkerd ,

This also happen on the example on the Tabulator site as you can see on the attached video...


https://user-images.githubusercontent.com/63957815/107669249-71c53100-6c89-11eb-9c1d-ee4bfc203b82.mp4

**Comment by rathboma** [comment]
I'm not sure if it 100% fixes this problem....but I think it does
