### ISSUE TITLE
Beta: Frozen column causes major padding-left issue when doing ajax refresh on the control

### ISSUE THREAD

**Issue by lac616** [olifolkerd/tabulator#344]
Hey there,

I figure it's best to describe the problem via screenshots.

![capture](https://cloud.githubusercontent.com/assets/27359692/26681672/edd8104e-46ab-11e7-9185-08ec60c1d935.PNG)
(Initial Ajax call)

This is the normal view. The left column "Item" is a frozen column. I use the following ajax call to refresh the grid when necessary: 
oTbl.tabulator("setData", baseUrl + pageUrl + "/GetMyItems", "{'param': " + JSON.stringify(param) + "}");

Each call increases the padding-left on the frozen column by 300px:
![capture1](https://cloud.githubusercontent.com/assets/27359692/26681819/62e8223e-46ac-11e7-8306-575336acecda.PNG)
(2nd call)

![capture2](https://cloud.githubusercontent.com/assets/27359692/26681859/814c4124-46ac-11e7-8487-a5c0daa8d9e6.PNG)
(3rd call)

It will continue to increase the padding left for each call.

Problem occurs in both IE and Chrome, does not occur in latest tabulator release.

Any further info you need please let me know - I can create a JSFiddle but I would need an Ajax URL source if you can provide one.

Thanks!

**Comment by olifolkerd** [comment]
Hey,

Could you post a copy of your Tabulator constructor as i cannot replicate this behaviour.

Also what browser are you using?

Many Thanks

Oli

**Comment by lac616** [comment]
Hi Oli,

Here is the constructor I am using:

```
var tabulatorOptions = {
        index: 'Comcode',
        height: '500',
        placeholder: "No items found for this group.",
        ajaxURL: baseUrl + pageUrl + "/GetMyItems", //ajax URL
        ajaxParams: "{'param': " + $MyItemParam.val() + "}", //ajax parameters
        ajaxConfig: {type:"POST", contentType: "application/json; charset=utf-8" }, //ajax HTTP request type
        tooltips: true,
        tooltipsHeader: true,
        progressiveRender: true,
        progressiveRenderSize: 5,
        progressiveRenderMargin: 100,
        showLoader: true,
        rowMoved: function (id, data, row, index) {

            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                url: baseUrl + pageUrl + "/ReorderGroup",
                data: "{'comcode': '" + data.Comcode + "', 'newIndex':'" + index + "', 'groupid':'" + $hidGroupId.val() + "'}",
                success: function (data) {

                }
            });

        },
        cellEdited: function (cell) {
            var data = cell.getRow().getData();
            var field = cell.getColumn().getField();
            if (field == 'UserItemGroupId') {
                
                var oldVal = cell.getOldValue();
                var newVal = cell.getValue();

                addMyItem(data.Comcode, newVal, false);
                deleteMyItem(data.Comcode, oldVal);

                
                var itemDesc = data.ShortDesc;
                var groupName = $('#ddlMyGroups').find('option[value="' + newVal + '"]').text();

                refreshGrid();

                $.growl.error({ title: '', message: '<strong>' + itemDesc + ' moved to Group: ' + groupName + '!</strong>', location: 'bl', duration: 5000 });

            }
        },
        groupBy: function (data) {

            if ($rbNone.prop('checked') == true) {
                return '';
            }

            if ($rbCategory.prop('checked') == true) {
                return data.Category;
            }

            if ($rbCatGroup.prop('checked') == true) {
                return data.Subcategory;
            }

            if ($rbQuoteDate.prop('checked') == true) {
                return data.QuoteDate;
            }

        },
        ajaxResponse: function (url, params, response) {
            var gridResponse = response.d;
            var dataViewId = $('.dataViewGroup').find('.active').find('.dataView').attr('data-id');

            //console.log(JSON.stringify(gridResponse.columns, replacer));
            //console.log(JSON.stringify(gridResponse.gridData, replacer));

            var cols = $.parseJSON(JSON.stringify(gridResponse.columns, replacer));
            var gridData = $.parseJSON(JSON.stringify(gridResponse.gridData, replacer));

            for (var i = 0; i < gridData.length; i++) {
                if (gridData[i].sparkline != undefined && gridData[i].sparkline !='') {
                    var arr= gridData[i].sparkline.split(',');
                    gridData[i].sparkline = arr;
                }
            }

            for (var i = 0; i < cols.length; i++) {
                if (cols[i].field == 'sparkline') {
                    cols[i].formatter = function (cell, formatterParams) {
                        setTimeout(function () { //give cell enough time to be added to the DOM before calling sparkline formatter
                            cell.getElement().sparkline(cell.getValue(), { width: "100%", type: "line", disableTooltips: true });
                        }, 10);
                    }
                }

                if (cols[i].title == 'Item') {
                    cols[i].formatter = historyLink;
                }

                if (cols[i].title == 'Del') {
                   // cols[i].title = 'Del';
                    cols[i].formatter = deleteItem;
                    cols[i].headerFilter = deleteItemHeader;

                }

                if (cols[i].title == 'Move Item') {
                    cols[i].editor = moveGroupEditor;
                    cols[i].formatter = moveItemName;
                    cols[i].headerFilter = headerMoveGroupEditor;
                }
            }

            if (dataViewId == "0" && $rbNone.prop('checked') == true) {
                this.movableRows = true;
              //  this.movableRowHandle = '<span class="fa fa-arrows-v"></span>';
            } else {
                this.movableRows = false;
             //   this.movableRowHandle = null;
            }


            $('#divTblView').tabulator("setColumns",cols, false);

            return gridData;
        },
        renderComplete: function () {
            if ($rbCategory.prop('checked') == true && $cbCategory.prop('checked') == false) {
                oTbl.tabulator('toggleColumn', 'Category');
            }

            if ($rbCatGroup.prop('checked') == true && $cbCatGroup.prop('checked') == false) {
                oTbl.tabulator('toggleColumn', 'Subcategory');
            }
        }

    }
    
    var oTbl = $('#divTblView').tabulator(tabulatorOptions);
```

As you can see from the above - my columns are created _dynamically_ based on user input. I think this may be the reason why the pixelation occurs.

If you still can't reproduce - I can create a JSFiddle, but I would need an ajax source to connect to as I believe it's a combination of ajax refresh and the frozen column. It occurs in both IE and Chrome.

Let me know if you need anything else. This is only occuring in BETA version - the latest release works properly with the above code.

Thanks!

**Comment by olifolkerd** [comment]
If the release version of 3.0 works correctly then i will mark this as resolved.

Thanks

Oli

**Comment by lac616** [comment]
3.0 Beta does not work. The 2.2 version works correctly with the constructor I posted. Are you able to reproduce? I will do my best to create a JSfiddle with an Ajax call. It's critical that this frozen column/pixel growth be fixed or unfortunately I will have to switch to another control.

**Comment by olifolkerd** [comment]
Hey,

Version 3.0 has now been released, hence my confusion over when version was "working".

Do you have a sample response to the ajax request to i can test this?

Many Thanks

Oli

**Comment by olifolkerd** [comment]
I have just pushed an update to the repo that should fix the issue,

let me know if that works for you.

Cheers

Oli

**Comment by lac616** [comment]
The update fixed it! Thank you!! I'm extremely pleased to keep working with this control. It is the most flexible grid control I've come across thus far, and as a developer I'm thrilled it creates divs instead of a table. I'll keep testing and keep you posted of any other issues.

**Comment by olifolkerd** [comment]
Hey,

Great to hear that got it working for you!

**Comment by lac616** [comment]
Ah...unfortunately this is not fixed after all :-(. If the frozen column overlays other columns (meaning we scrolled horizontally to the right), it will cause the same padding problem when ajax is used to refresh, plus it will override any new columns created dynamically. 

It's hard to describe what I'm seeing so I will create a jsfiddle.

**Comment by lac616** [comment]
OK, I think I found the problem. As mentioned previously, I am creating the columns dynamically based on user input with the following line: 
` $('#divTblView').tabulator("setColumns",cols, false);`
(which btw - it appears the boolean parameter is no longer used in Beta 3 with the new ColumnManager but the documentation still specifies that it does).

I have one frozen column which is not grouped. I recreated the problem by scrolling horizontally to the right-most columns, then doing an ajax refresh, which called the setColumns method. In your ColumnManager, it clears the columns, but never adjusts the scrollLeft position. Therefore, the layout still thinks the frozen margin of the frozen column should be the right-most position. I added the following line to your setColumns method and the extra padding is now fixed:

![capture](https://user-images.githubusercontent.com/27359692/27103282-1f5bf406-5056-11e7-92c5-955304a94e90.PNG)

I will leave it to you to review and decide if this should be permanent.

Thanks!

**Comment by olifolkerd** [comment]
Hey,

Thanks for the extra details, the second parameter to the  ***setColumns*** function should be there, so that is definitely a bug.

you are also spot on about the scroll position not resetting on column update, i will get that in this weekend too.

**Comment by lac616** [comment]
Excellent. FYI - the solution I proposed regarding scrollLeft and setColumns works when rows are grouped. When rows are ungrouped, scrollLeft does indeed reset to 0 but the horizontal bar maintains it's position, causing rows to be skewed from the headers. As soon as the horizontal bar is moved, it realigns properly.

**Comment by olifolkerd** [comment]
Hey,

I have added some additional functions to handle getting and setting column layouts, see #362 for more details... I will update the documentation to remove second parameter from setColumns,

I have just committed some changes to the 3.1 branch that should fix the issues you were having when setting columns,

There should be an official release of 3.1 by the end of this weekend.

Cheers

Oli

**Comment by lrowleyUB** [comment]
Hi Oli,

I'm having this problem again. Here is the situation:

On my first ajax call, I load the grid with a set of columns where the first 3 have frozen:true. When the user clicks a tab, I make a second ajax call and retrieve a _different_ set of columns where none are frozen. The first column of the second call has large padding-left set and I can't seem to clear it:

![capture](https://user-images.githubusercontent.com/33427660/35983780-d9ee5c06-0cc0-11e8-899e-3d98701e931c.PNG)

I've tried both of the following to clear and reset column definitions in the ajaxResponse:
$('#tblNoLoginActivity').tabulator("setColumnLayout", cols);
$('#tblNoLoginActivity').tabulator("setColumns", cols);

Any advice?

Thanks,
Laura

**Comment by olifolkerd** [comment]
Hey @lrowleyUB 

Which version of Tabulator are you using.

Do you have an example of your table constructor/coulmn definitions so i can run a test?

Cheers

Oli :)
