### ISSUE TITLE
replaceData() or setData() fails on grouped tables

### ISSUE THREAD

**Issue by simonhbw** [olifolkerd/tabulator#3589]
**Describe the bug**
When Grouping is enabled, i cannot replace/refresh the table data using replaceData or setData after the initial rendering. when i execute setData or replaceData, the table gets renderd again and again. Tabulators group.js is throwing thousands of uncaught typeErrors:
`Group.js:170 Uncaught TypeError: Cannot set properties of undefined (setting 'marginLeft')
    at e.value (Group.js:170:27)
    at GroupRows.js:563:10
    at Array.forEach (<anonymous>)
    at n.value (GroupRows.js:562:18)
    at InternalEventBus.js:119:42
    at Array.forEach (<anonymous>)
    at e.value (InternalEventBus.js:118:21)
    at r.value (CoreFeature.js:78:30)
    at r.value (RowManager.js:570:8)
    at n.value (VirtualDomVertical.js:107:25)`

**Tabulator Info**
- Which version of Tabulator are you using?
>5.1.0

**Working Example**
https://jsfiddle.net/#&togetherjs=lllFVgMEle

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. enable groupBy on any field
2. call table.setData() or table.replaceData()

**Expected behavior**
Table Data refreshes and table renders

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 98.0.4758.82

**Comment by olifolkerd** [comment]
Hey @simonhbw 

This all seems to be working my end without any issue. which likely means it is a result of a specific table configuration. Unfortunately you appear to have included a link to an empty JS Fiddle. Without seeing how your table is configured im afraid i wont be able to diagnose the issue.

Please link to a working fiddle that shows a minimal table configuration that replicates this issue and i can look into it further

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@simonhbw do you have a link to a working JS Fiddle? im afraid if i cant recreate this i will need to close the issue.

Cheers 

Oli :)

**Comment by simonhbw** [comment]
dear @olifolkerd 

im sorry for the invalid jsfiddle link. please take a look at the new jsfiddle:
https://jsfiddle.net/zkq65Lrj/6/

kind regards

**Comment by olifolkerd** [comment]
Hey @simonhbw 

Thanks for the info, that was helpful. I have pushed a fix to master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by guilhemmarchand** [comment]
Hi @olifolkerd 

Can you confirm that the latest version (5.1.7) in the master branch had addressed this issue?
I am encountering the same problem with grouped table, and did update to the latest, however I still get the same exact issue that was described here.

Thank you!

**Comment by guilhemmarchand** [comment]
Using:
```
table.updateOrAddData(resultCall);
```
Fixed all my issues including the grouping issue
