### ISSUE TITLE
Persistence doesn't save column visibility (reappearing hidden columns)

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3724]
Tabulator persistence mode is not saving column visibility:

![persistence-not-hidden](https://user-images.githubusercontent.com/279769/165666351-87901e19-29b0-4852-a3fb-124364dcf7cf.gif)

Steps to reproduce:
- hide columns
- refresh page

expected:
- columns should be hidden

actual:
- the columns [came back](https://www.youtube.com/watch?v=OE8gsYejpQc)!

Config used:

```
	persistence: { columns: true },
	persistenceID: '1'
```

**Comment by JacobGralinski** [comment]
Hi @rathboma I found that explicitly stating visibility on each column allows that data to persist. Not sure if it's supposed to persist without it being a part of the column config, so it could still be a bug in that sense.

`visible:  true
visible: false`

**Comment by olifolkerd** [comment]
Hey @rathboma 

This was happening because the persistence module was only tracking the values of keys that had actually been seen in the column definitions.

As the documentation clearly states setting `colums:true` should include the visibility, i have just pushed a fix for this to the master branch and will include it in todays patch release.

It will now forcibly include the column visibility if `columns` is set to `true`.


@JacobGralinski as a helpful hint for you, if you need to set a value on every column, then rather than setting it manually on every column, you can use the `columnsDefaults` option in the constructor, any value in this object will be applied to all columns:
````js
var table = new Tabulator("#example-table", {
    columnDefaults:{
        visible:true,    },
});
```

Cheers

Oli :)

**Comment by rtconner** [comment]
@olifolkerd When using `table.hideColumn("field")` setting `"columnDefaults:{visible:true},"` does not solve this problem on 6.3 -- I still have to set visible:true on each column
